### PR TITLE
fix: pin flask version for compatibility with mara-app

### PR DESCRIPTION
**Pull request by amanji**

### CODE REVIEW

**Comment by amanji** [comment]
@WadeBarnes @esune

**Review by esune — COMMENTED** [review]
If this works, would it be possible/preferable to also pin the other two dependencies listed in the Dockerfile in the requirements file, rather than having them inlined there?

**Comment by amanji** [comment]
Yeah. Was mentioning the same thing to @WadeBarnes. But I think it's best to commit a separate PR for that.

**Comment by amanji** [comment]
Removing those RUN arguments will also reduce the number of layers in the image going forward.

**Review by WadeBarnes — APPROVED** [review]

**Pull request merged**
