### PR TITLE
Enable issue cred v20 protocol for BC Reg issuer

### PR DESCRIPTION
**Pull request by ianco**
Add support for v20 credential exchange.  Specify the protocol to use using the env var `ISSUE_CRED_VERSION` - values are `V10` and `V20` (default is `V10` if not specified).

This can be set for the container, or specifically for the cred submitter job as follows:

```
ISSUE_CRED_VERSION=V20 ./run-step.sh bcreg/submit-creds.py
ISSUE_CRED_VERSION=V20 ./run-step.sh bcreg/submit-creds_lear.py
```

### CODE REVIEW

**Review by esune — DISMISSED** [review]
LGTM 👍🏻 

@WadeBarnes I'll let you merge it when it is best to get the changes deployed and assessed in `dev`

**Comment by esune** [comment]
@ianco unsurprisingly this PR has become a bit stale and there are conglicts that need resolving now. Mind taking a quick look?

**Comment by WadeBarnes** [comment]
Are there any dependencies on the OrgBook side required for this to work?  Also we have some comments here (https://github.com/bcgov/von-bc-registries-agent-configurations/pull/79#issuecomment-2133976615) about the order we want to upgrade the ACA-Py versions.  Are theses changes independent of those updates?

**Comment by esune** [comment]
> Are there any dependencies on the OrgBook side required for this to work? Also we have some comments here ([bcgov/von-bc-registries-agent-configurations#79 (comment)](https://github.com/bcgov/von-bc-registries-agent-configurations/pull/79#issuecomment-2133976615)) about the order we want to upgrade the ACA-Py versions. Are theses changes independent of those updates?

I *think* if we use V10 things should work as they are now. If we switch to V20 we would have to update the OrgBook side as well since the webhook payload would be slightly different.

**Review by esune — APPROVED** [review]
LGTM 👍🏻

**Review by WadeBarnes — APPROVED** [review]

**Comment by WadeBarnes** [comment]
Changes have been deployed to `dev` and `test`.
cc @ianco @esune

**Pull request merged**
